install.packages("readxl")
NFLDraftProject<-read_excel(file.choose())
View(NFLDraftProject)
print(NFLDraftProject)
cor(NFLDraftProject$Order, NFLDraftProject$`Prospect Grade`)
cor(NFLDraftProject$Order, NFLDraftProject$Experience)
cor(NFLDraftProject$Experience, NFLDraftProject$`National Awards`)
cor(NFLDraftProject$Order, NFLDraftProject$`National Awards`)
cor(NFLDraftProject$Order, NFLDraftProject$`Strength of Conference`)
levels(NFLDraftProject$Order)
print(NFLDraftProject$Order)
print(NFLDraftProject$Experience)
plot(NFLDraftProject$`Prospect Grade`, NFLDraftProject$Order)
scatter.smooth(x=NFLDraftProject$`Prospect Grade`,y=NFLDraftProject$Order)
par(mfrow=c(1,2))
boxplot(NFLDraftProject$`Prospect Grade`, main="Prospect Grade", sub=paste("outlier rows:", boxplot.stats(NFLDraftProject$`Prospect Grade`)$out))
plot(NFLDraftProject$`Position Value`, NFLDraftProject$Order)
plot(NFLDraftProject$`Strength of Conference`, NFLDraftProject$Order)
Draftmodel<-lm(NFLDraftProject$Order~NFLDraftProject$`Strength of Conference`+NFLDraftProject$`Prospect Grade`+NFLDraftProject$`40 time`+NFLDraftProject$`Bench Press > 20`+NFLDraftProject$`National Awards`+NFLDraftProject$Experience+NFLDraftProject$DET_RB+NFLDraftProject$DET_DL+NFLDraftProject$DET_CB+NFLDraftProject$DET_T+NFLDraftProject$DET_WR+NFLDraftProject$MIA_S+NFLDraftProject$MIA_EDGE+NFLDraftProject$MIA_QB+NFLDraftProject$MIA_RB+NFLDraftProject$MIA_T+NFLDraftProject$CIN_QB+NFLDraftProject$CIN_LB+NFLDraftProject$CIN_WR+NFLDraftProject$CIN_T+NFLDraftProject$CIN_TE+NFLDraftProject$WAS_CB+NFLDraftProject$WAS_EDGE+NFLDraftProject$WAS_T+NFLDraftProject$WAS_TE+NFLDraftProject$WAS_WR+NFLDraftProject$NYG_EDGE+NFLDraftProject$NYG_S+NFLDraftProject$NYG_T+NFLDraftProject$NYG_TE+NFLDraftProject$NYG_WR, data =NFLDraftProject)
summary(Draftmodel)
Draftmodel2<-lm(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB, data = NFLDraftProject)
summary(Draftmodel2)
plot(Draftmodel2)
plot(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB, data = NFLDraftProject)
plot(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB, data = NFLDraftProject)
abline(lm(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB), col="red")
scatter.smooth(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB, data = NFLDraftProject)
plot(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB)
plot(x=NFLDraftProject$`Prospect Grade`,y=NFLDraftProject$Order, main = "Draft order~Prospect Grade (Pre-Draft)")
lm(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`)
summary(lm(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`))
abline(lm(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`), col="red")
cor(NFLDraftProject$`Prospect Grade`,NFLDraftProject$Order)
plot(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB, data = NFLDraftProject)
scatter.smooth(NFLDraftProject$Order~NFLDraftProject$`Prospect Grade`+NFLDraftProject$MIA_QB, data = NFLDraftProject)
library(readxl)
NFLDraftProject2<-read_excel(file.choose())
Draftmodel3<-lm(NFLDraftProject2$`True Order`~NFLDraftProject2$`Prospect Grade`+NFLDraftProject2$MIA_QB, data = NFLDraftProject2)
print(Draftmodel3)
summary(Draftmodel3)
plot(NFLDraftProject2$`True Order`~NFLDraftProject2$`Prospect Grade`+NFLDraftProject2$MIA_QB, data = NFLDraftProject2)
scatter.smooth(NFLDraftProject2$`True Order`~NFLDraftProject2$`Prospect Grade`+NFLDraftProject2$MIA_QB, data = NFLDraftProject2)
plot(Draftmodel3)
FirstRound<-read_excel(file.choose())
DraftModel4<-lm(FirstRound$`First Round Order`~FirstRound$`Prospect Grade`+FirstRound$MIA_QB, data = FirstRound)
summary(DraftModel4)
plot(x=FirstRound$`Prospect Grade`,y=FirstRound$`First Round Order`, main ="Draft order~Prospect Grade (Post Draft)" )
lm(FirstRound$`First Round Order`~FirstRound$`Prospect Grade`)
abline(lm(FirstRound$`First Round Order`~FirstRound$`Prospect Grade`), col="red")
summary(lm(FirstRound$`First Round Order`~FirstRound$`Prospect Grade`))
       
                                                                                                                                                                                  